
const All_Prescription = [
    {
        prescId: 1,
        prescDate: 'Sep 2, 2022 ',
        patientId:1,
        patientName: 'Abebaw Esubie',
        age: 19,
        Gender:'male',
        patientPhone: '09-13-14-15-16',
        medicationName: 'paractamol',
        purpose: 'for fever',
        dosage: '1 tablet',
        route: 'oral',
        frequency: 'every 4 hours',
        physicianName: 'Dr. Temesgen Asrat',
        physicianEmail: 'tamme@gmail.com',
        Phone: '09-12-14-15-16',

    },
    {
        prescId: 2,
        prescDate: 'Oct 2, 2022 ',
        patientId:1,
        patientName: 'Abebaw Esubie',
        age: 19,
        Gender:'male',
        patientPhone: '09-78-14-15-16',
        medicationName: 'paractamol',
        purpose: 'for fever',
        dosage: '1 tablet',
        route: 'oral',
        frequency: 'every 4 hours',
        physicianName: 'Dr. Temesgen Asrat',
        physicianEmail: 'tamme@gmail.com',
        Phone: '09-17-14-15-16',

    },
    {
        prescId: 3,
        prescDate: 'Jan 2, 2023',
        patientId:1,
        patientName: 'Abebaw Esubie',
        age: 20,
        Gender:'male',
        patientPhone: '09-33-14-15-16',
        medicationName: 'Vitamin C',
        purpose: 'Immune System',
        dosage: '500mg',
        route: 'oral',
        frequency: 'every 8 hours',
        physicianName: 'Dr. Abebe Aregay',
        physicianEmail: 'abe@gmail.com',
        Phone: '09-19-14-15-16',

    },
    {
        prescId: 4,
        prescDate: 'Apr 2, 2023 ',
        patientId:1,
        patientName: 'Abebaw Esubie',
        age: 20,
        Gender:'male',
        patientPhone: '09-13-14-15-16',
        medicationName: 'Vitamin C',
        purpose: 'Immun System',
        dosage: '1 tablet',
        route: 'oral',
        frequency: 'Once a Day',
        physicianName: 'Dr.Degu Alemayehu',
        physicianEmail: 'degu@gmail.com',
        Phone: '09-82-14-15-16',

    },
    {
        prescId: 5,
        prescDate: 'Jun 2, 2024',
        patientId:1,
        patientName: 'Abebaw Esubie',
        age: 21,
        Gender:'male',
        patientPhone: '09-13-14-15-16',
        medicationName: 'paractamol',
        purpose: 'for fever',
        dosage: '1 tablet',
        route: 'oral',
        frequency: 'every 4 hours',
        physicianName: 'Dr. Askalu Demeke',
        physicianEmail: 'aske@gmail.com',
        Phone: '09-15-56-15-16',

    },
    {
        prescId: 6,
        prescDate: 'July 2, 2024',
        patientId:1,
        patientName: 'Abebaw Esubie',
        age: 21,
        Gender:'male',
        patientPhone: '09-13-14-15-16',
        medicationName: 'paractamol',
        purpose: 'for fever',
        dosage: '1 tablet',
        route: 'oral',
        frequency: 'every 4 hours',
        physicianName: 'Dr. Askalu Demeke',
        physicianEmail: 'aske@gmail.com',
        Phone: '09-12-14-45-16',

    },
]


export default All_Prescription


